### ISSUE TITLE
[Enhancement] Add support to multilingual

### ISSUE THREAD

**Issue by RodrigoTomeES** [ObuchiYuki/DevToysMac#10]
Hi,

Can add support for multilingual? The strings are hardcoded so first it's necesary to extract it. I never worked with Swift so I can't help with this problem but I can translate the app to Spanish.

Thanks!

**Comment by ObuchiYuki** [comment]
Thanks!!!

In the next release, we'll be able to split up the other language files so we can translate them!

**Comment by ObuchiYuki** [comment]
@RodrigoTomeES Thank you for your issue!
I did implement multilingual support to this release https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.7.2
Now it supports only Japanese, but I'll continuously update the localizations!

**Comment by RodrigoTomeES** [comment]
> @RodrigoTomeES Thank you for your issue!
> I did implement multilingual support to this release https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.7.2
> Now it supports only Japanese, but I'll continuously update the localizations!

Hi,

Great, I saw it in the commits and I am already working to translate it to Spanish 🚀.

**Comment by ObuchiYuki** [comment]
@RodrigoTomeES 
Thank you very much! Lo estamos deseando.
