### ISSUE TITLE
[BUG] Hash Generator's initial values are all "Hello World"

### ISSUE THREAD

**Issue by qqhann** [ObuchiYuki/DevToysMac#13]
When I first run the app and go to Hash Generator, the initial values are all "Hello World".
I suppose it should better be hashed values even if it is the first time you run the app.

Once I changed the Input value, this is fixed and I couldn't provide a screenshot.

**Comment by ObuchiYuki** [comment]
Thanks for reporting the bug!
I understand the bug about Initial Value.
Please wait to approve the PR as we are currently working on the integration with DevToys for Windows and the Initial Value itself may disappear.

I will move forward with the PR as soon as the DevToys for Windows integration is resolved.

**Comment by nicolalazzaro** [comment]
The exact same thing happens to me on MacBook Pro (16-inch, 2019) Intel, it would be better to display the encoded string from the first start as suggested.
