### ISSUE TITLE
Will there ever be a new version?

### ISSUE THREAD

**Issue by tvdsluijs** [ObuchiYuki/DevToysMac#139]
I really love this tool!!! But the DevToys app release is now on version v1.0.13.0. And version 2.0 is coming up!

Will this MAC port ever get new updates? Or get an 2.0 version???

**Comment by RodrigoTomeES** [comment]
I think the project is dead

**Comment by veler** [comment]
Hi,
I'm the author of the original DevToys app (for Windows).
I'm currently working on DevToys 2.0. We keep adding more tools, address feedback and add new features.
DevToys 2.0 will work on Windows and Mac. You can follow the development on GitHub https://github.com/veler/DevToys or on Twitter where I occasionally post some screenshots of what's coming up. https://twitter.com/VelerSoftware

Here is a fresh screenshot. Of course, it's a work in progress.

![image](https://github.com/ObuchiYuki/DevToysMac/assets/3747805/dac1718e-3876-4568-8262-2be8d7692914)

@ObuchiYuki, as you don't seem to maintain this project anymore, it might be a good idea to consider [Archiving this repository](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) and redirect people toward the original one to avoid confusing the customers: https://github.com/veler/DevToys

**Comment by moranmono** [comment]
Great new!!!

**Comment by tvdsluijs** [comment]
Hi @veler that is great news!!!!!! 2 questions.

1. Do you need Mac testers? If so let me know.
2. Will you be adding it to [Brew](https://brew.sh)

**Comment by veler** [comment]
> Do you need Mac testers? If so let me know.

We will definitely need once we get a preview release, but we're still a few months away from it.

> Will you be adding it to [Brew](https://brew.sh/)

It's on of the channel of distribution we're considering, yes, along with a few others.
