### ISSUE TITLE
Text diff feature

### ISSUE THREAD

**Issue by shinichy** [ObuchiYuki/DevToysMac#15]
Thanks for creating a great app so quickly! It would be great if DevToysMac could support Text diff functionality.

**Comment by ObuchiYuki** [comment]
@shinichy Thank you for your issue! I haven't implemented this in DevToys for mac due to the difficulty of implementation, but I'll get to it before the next release! Thank you.

**Comment by RodrigoTomeES** [comment]
@ObuchiYuki Hi, I found this repo https://github.com/DevUtilsApp/DevUtils-app that is implement in Swift and has text diff, JSON inspector #16, search functionality in JSON #36... But the project has CC license that doesn't support create derivative works so you can get the idea about they implement it but not copy and paste their code 😅

**Comment by ObuchiYuki** [comment]
@shinichy @RodrigoTomeES  With your help, I was able to implement the Text Diff feature!
I was able to find the OSS that "DevUtils" depended on, and installing that OSS solved the problem! Thank you so much!



![画面収録 2022-02-23 15 07 59](https://user-images.githubusercontent.com/20896810/155270131-89f750dc-ce2e-4ef0-9e91-b3f2b1ba3e6e.gif)

**Comment by ObuchiYuki** [comment]
@shinichy  @RodrigoTomeES Added in v0.0.10!

https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.10
