### ISSUE TITLE
Feature request: text escape/unescape

### ISSUE THREAD

**Issue by lizy14** [ObuchiYuki/DevToysMac#155]
the Windows app has this, and I use it quite often

<img width="1280" alt="image" src="https://github.com/DevToys-app/DevToysMac/assets/9985286/56c51fc8-fd17-412e-89e4-c926bb6bb33e">

**Comment by veler** [comment]
Hello,
Great news! DevToys 2.0 is coming on Windows Mac and Linux, and it has this tool :)
It will be released later this spring.
