### ISSUE TITLE
"Check For Updates..." feature

### ISSUE THREAD

**Issue by victordidenko** [ObuchiYuki/DevToysMac#17]
Or at least, add link to this repository in the "About" window, so it will be possible to go and check manually, is new version available :)

**Comment by ObuchiYuki** [comment]
@victordidenko 

Implemented, will be available in v0.0.9!

![画面収録 2022-02-22 23 30 20](https://user-images.githubusercontent.com/20896810/155153123-c74fdfe7-03ce-41a3-b0bf-cde6870850b5.gif)
