### ISSUE TITLE
Request to posted Homebrew version

### ISSUE THREAD

**Issue by SAMZONG** [ObuchiYuki/DevToysMac#18]
It's really convenient

**Comment by jaroslavmraz** [comment]
brew install --cask devtoys

**Comment by Senlan0528** [comment]
> brew install --cask devtoys

`Cask 'devtoys' is unavailable: No Cask with this name exists.`

**Comment by xzzz2020** [comment]
> > brew install --cask devtoys
> 
> `Cask 'devtoys' is unavailable: No Cask with this name exists.`

I have the same problem.

**Comment by jaroslavmraz** [comment]
Did you update before? 

Its working for me.

https://formulae.brew.sh/cask/devtoys#default

**Comment by Senlan0528** [comment]
> 

I handeled it.Maybe you need proxy.

**Comment by Senlan0528** [comment]
> > > brew install --cask devtoys
> > 
> > 
> > `Cask 'devtoys' is unavailable: No Cask with this name exists.`
> 
> I have the same problem.

I handeled it.Maybe you need proxy.
