### ISSUE TITLE
Please add support for RGB to hex and vice versa 

### ISSUE THREAD

**Issue by nebula-byte** [ObuchiYuki/DevToysMac#19]

**Comment by ObuchiYuki** [comment]
@nebula-byte Thank you for your issue!
I think this feature should be a one part of a Color Picker Tool!
I'll implement this in next update!

**Comment by optikfluffel** [comment]
@ObuchiYuki: while you're at it: HSL colors would also be very helpful 😊
🏆 Bonus points for alpha channel support 😋

**Comment by ObuchiYuki** [comment]
@nebula-byte  @optikfluffel 

Added on 0.0.8!
<img width="1030" alt="スクリーンショット 2022-02-20 12 01 10" src="https://user-images.githubusercontent.com/20896810/154826895-e41472cd-4422-4e39-a529-4994dcb43848.png">

https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8.2
