### ISSUE TITLE
Color theme should match the OS theme

### ISSUE THREAD

**Issue by newadventure079** [ObuchiYuki/DevToysMac#22]
Rather than have the app's theme hardcoded to dark, there should be a choice of dark, light or match the OS theme

**Comment by ObuchiYuki** [comment]
I did update this! You can use OS theme in DevToys for mac on next update!

<img width="1051" alt="スクリーンショット 2022-02-14 12 46 50" src="https://user-images.githubusercontent.com/20896810/153796952-3e17759b-aca5-4bfc-808d-e884f79c6c80.png">
<img width="1051" alt="スクリーンショット 2022-02-14 12 47 07" src="https://user-images.githubusercontent.com/20896810/153796960-8f004e8c-9e4d-456b-acbb-07f40bced1f8.png">
