### ISSUE TITLE
Typo in description of "Text Case Converter and Inspector" on All Tools

### ISSUE THREAD

**Issue by mpozderac** [ObuchiYuki/DevToysMac#29]
![image](https://user-images.githubusercontent.com/13731811/153640429-0740b92e-674c-4fa1-8cdb-fa2c22521480.png)

**Comment by ObuchiYuki** [comment]
@mpozderac 
Thank you!!! This PR was merged!
https://github.com/ObuchiYuki/DevToysMac/pull/31/commits/ba9bb62e9fad23e63d490d0684ef88725266689a
