### ISSUE TITLE
Typo: HEML -> HTML

### ISSUE THREAD

**Issue by wakuto** [ObuchiYuki/DevToysMac#3]
HEML Encoder / Decoder -> HTML Encoder / Decoder
![img](https://user-images.githubusercontent.com/20896810/151695300-e0dccd31-b3ac-42e6-904d-d287e56e4e63.png)

**Comment by ObuchiYuki** [comment]
Thank you. I'll fix that.

**Comment by ObuchiYuki** [comment]
fixed!

**Comment by neutric** [comment]
Depending on how picky you are, you might also want to update the screenshot showcasing this Encoder/Decoder in [README.md](https://github.com/ObuchiYuki/DevToysMac/blob/main/README.md).
