### ISSUE TITLE
Add a search functionality

### ISSUE THREAD

**Issue by sniranjan** [ObuchiYuki/DevToysMac#36]
Really appreciate your effort, just downloaded the latest release and it looks amazing. 

One request though, currently there is no way to search any record. I have huge JSON files, it would be nice to see them in a tree view and search by keys or values. You can refer to https://jsoneditoronline.org/. The code is also Apache licensed,  https://github.com/josdejong/jsoneditor.

**Comment by ObuchiYuki** [comment]
@sniranjan Thank you for your issue!
That's interesting. DevToys for mac is running on Swift, so I can't use it as is, but I can use it as a reference. it would be interesting to have it as a function of JSON Formatter.

**Comment by RodrigoTomeES** [comment]
@ObuchiYuki I have been searching for a while and I have seen that it is possible to run JS in Swift. I don't know if it's recommended, but this documentation is still useful for you.

https://medium.com/academy-eldoradocps/javascript-and-swift-66c59bf2317e
https://developer.apple.com/documentation/javascriptcore

**Comment by ObuchiYuki** [comment]
@sniranjan @RodrigoTomeES 
Hello! I've added a search function to CodeTextView! You can now search in almost any CodeTextView!

![画面収録 2022-02-25 18 18 28](https://user-images.githubusercontent.com/20896810/155689178-7eeefde3-651c-4fbc-a18f-5816cc77f04d.gif)
