### ISSUE TITLE
UI Visual Clean-up

### ISSUE THREAD

**Issue by austincondiff** [ObuchiYuki/DevToysMac#40]
I am noticing several UI inconsistencies as follows.

The sidebar spacing is a bit off. I've corrected it and this is the result. I am showing it alongside Finder to show how it should look.
![image](https://user-images.githubusercontent.com/806104/153930509-3dc41c03-35ed-43d2-a0fc-2d92cf85b7e7.png)

We may even consider replacing categories with collapsable list section headings instead of using an outline view (similar to the FInder sidebar - "Favorites", "iCloud", "Locations", "Tags"). This would save space and flatten up our navigation.

Changing `ToolmenuCell` to this should fix this. Then resize all the icon image files from 16x16 to 20x20 (or just download the resized files [here](https://github.com/ObuchiYuki/DevToysMac/files/8063454/sidebar.zip)).

```swift
import CoreUtil

final class ToolmenuCell: NSLoadView {
    
    static let height: CGFloat = 28
    
    var title: String {
        get { titleLabel.stringValue } set { titleLabel.stringValue = newValue }
    }
    var icon: NSImage? {
        get { iconView.image } set { iconView.image = newValue }
    }
    
    private let titleLabel = NSTextField(labelWithString: "Title")
    private let iconView = NSImageView()
    
    override func onAwake() {
        self.snp.makeConstraints{ make in
            make.height.equalTo(Self.height)
        }
        self.addSubview(iconView)
        self.iconView.snp.makeConstraints{ make in
            make.size.equalTo(20)
            make.left.equalTo(0)
            make.centerY.equalToSuperview()
        }
        self.addSubview(titleLabel)

        self.titleLabel.lineBreakMode = .byTruncatingTail
        self.titleLabel.font = .systemFont(ofSize: R.Size.controlTitleFontSize)
        self.titleLabel.snp.makeConstraints{ make in
            make.left.equalTo(self.iconView.snp.right).offset(4)
            make.right.equalToSuperview().inset(4)
            make.centerY.equalToSuperview()
        }
    }
}
```

The search bar is too small. See the search bar in Music, Finder, App Store or any other app and see that it should be a bit taller.
![image](https://user-images.githubusercontent.com/806104/153931090-ca4235eb-61c7-421b-861f-0d5bb03a81ca.png)

The search bar should also scroll with the overflow and when scrolled, a subtle line should appear dividing the window controls from the sidebar content.
![image](https://user-images.githubusercontent.com/806104/153931688-50226c37-4665-4c2d-8347-c378f0e36ddb.png)
(You get most of this for free by the way with SwiftUI, so we may consider using it instead.)

I am also noticing that there is unnecessary overflow on some of the screens where the text inputs are sized to fit the window height.

**Comment by ObuchiYuki** [comment]
@austincondiff Thank you for your issue!!! I also think it is very important to be like native app. Thank you for all the materials. Thanks to your help, I was able to do the modification easily.

This is what it looks like now. It now looks more like Apple's music app.

<img width="291" alt="スクリーンショット 2022-02-16 13 15 55" src="https://user-images.githubusercontent.com/20896810/154195402-c65d8aa7-86b5-48a7-886c-47acef27621d.png">

And the overflow problem is solved!


<img width="262" alt="スクリーンショット 2022-02-16 13 21 10" src="https://user-images.githubusercontent.com/20896810/154195628-4d1f9f1d-3895-4bea-bda4-e8eb23f3a1a9.png">

**Comment by austincondiff** [comment]
@ObuchiYuki Very nice work, looks perfect. I am new to Swift (coming from React) so I am not as familiar with Cocoa (mainly just SwiftUI) otherwise I would have just submitted a PR. Glad to see it didn't take you too long, I spent a whole weekend trying to figure out how to replace the NSOutlineView with subheadings and navigation items. 😅

**Comment by ObuchiYuki** [comment]
@austincondiff Thank you for your support and I fixed this on https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8.2
