### ISSUE TITLE
"Encoded" and "Decoded" are swapped

### ISSUE THREAD

**Issue by ruudwelten** [ObuchiYuki/DevToysMac#42]
Great tool guys! I just noticed a little quirk, under Encoders / Decoders the terminology for decoding and encoding is swapped:

For HTML and URL the "Encoded" textarea shows the decoded text and vice versa.
<img width="466" alt="Screenshot 2022-02-15 at 15 13 57" src="https://user-images.githubusercontent.com/1828953/154079409-401a514f-4fb8-4565-b135-667d8e986753.png">
<img width="220" alt="Screenshot 2022-02-15 at 15 09 07" src="https://user-images.githubusercontent.com/1828953/154079411-76df0175-15a3-4e6b-9d46-911e094c9393.png">

Also for Base64 encoding/decoding the bottom textarea should say "Encoded".
<img width="364" alt="Screenshot 2022-02-15 at 15 14 04" src="https://user-images.githubusercontent.com/1828953/154079396-649afb58-ee0c-44af-bdce-958154d2f5c4.png">

Edit: And a little addition: I noticed, the UUID Generator is called "Hash" in the sidebar.
<img width="188" alt="Screenshot 2022-02-15 at 21 54 10" src="https://user-images.githubusercontent.com/1828953/154147567-f471da0b-e65c-4d76-86f3-4720464c7eb1.png">

**Comment by ObuchiYuki** [comment]
@ruudwelten Thank you! I'll fix that!

UUID <>  Hash was fixed with this PR! https://github.com/ObuchiYuki/DevToysMac/pull/38

**Comment by ObuchiYuki** [comment]
@ruudwelten  Thank you and fixed on v0.0.8  https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8.2
