### ISSUE TITLE
Resize textarea of JWT

### ISSUE THREAD

**Issue by g-ongenae** [ObuchiYuki/DevToysMac#47]
The UI of the JWT encoder/decoder would be better if instead of looking like this (⏬), it looked like the UI for the Base64 encoder/decoder.

It should be full screen like the other view.

![Capture d’écran 2022-02-16 à 16 09 47](https://user-images.githubusercontent.com/9453090/154294207-c8ed1d95-9084-48e7-bd64-40b4ff6985dc.png)

![Capture d’écran 2022-02-16 à 16 09 56](https://user-images.githubusercontent.com/9453090/154294216-f2570e08-0970-47f1-a97c-f839f9027371.png)

(I'll glady work on it this weekend if needed.)

**Comment by ObuchiYuki** [comment]
@g-ongenae Thank you for your issue! I did fix that!

<img width="1130" alt="スクリーンショット 2022-02-17 12 39 00" src="https://user-images.githubusercontent.com/20896810/154400777-833a2530-b503-40a3-991e-d609fd2490bf.png">

**Comment by ObuchiYuki** [comment]
@g-ongenae  Fixed on https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8
