### ISSUE TITLE
Remove focus from input when clicking outside

### ISSUE THREAD

**Issue by itizarsa** [ObuchiYuki/DevToysMac#58]
Today when I was playing with devtoys, i thought it would be better to remove focus from input elements when we click outside of the input box

https://user-images.githubusercontent.com/77574889/154604762-74a83720-d6ef-4558-a08b-1851e2278555.mov

**Comment by ObuchiYuki** [comment]
@itizarsa Thanks for noticing that! But I think that behavior is very natural on a mac! (Similar to Preference.) If you have a different intention, please let me know!


https://user-images.githubusercontent.com/20896810/154781872-f2e46524-04d8-44e2-98a8-14eddae04370.mov
