### ISSUE TITLE
JSON <> YAML & JSON Formatter not working properly

### ISSUE THREAD

**Issue by itizarsa** [ObuchiYuki/DevToysMac#59]
When I'm using JSON <> YAML, I couldn't find the conversion option shown in the screenshot. Also, my JSON is not being converted to YAML

Also, the JSON formatter is not highlighting the syntax

https://user-images.githubusercontent.com/77574889/154605579-be870853-2a80-417e-bb4f-43a458bfe068.mov

**Comment by ObuchiYuki** [comment]
@itizarsa Thank you for your issue! 
It seems to be a problem with the quart that is being mentored here: https://github.com/ObuchiYuki/DevToysMac/issues/45 

The fix is finished in 0.0.8.

https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8.2
