### ISSUE TITLE
UUID Generator Typo

### ISSUE THREAD

**Issue by itizarsa** [ObuchiYuki/DevToysMac#60]
In the devtoys sidebar, UUID generator is named as Hash

<img width="729" alt="SS1 2022-02-18 at 07 53 25 " src="https://user-images.githubusercontent.com/77574889/154605735-bdf29bdb-e307-40ad-9253-b33069bd3d13.png">

**Comment by ObuchiYuki** [comment]
Duplicated https://github.com/ObuchiYuki/DevToysMac/pull/38
