### ISSUE TITLE
[Feature Request] Text diff checker

### ISSUE THREAD

**Issue by itizarsa** [ObuchiYuki/DevToysMac#61]
<img width="1221" alt="SS1 2022-02-18 at 07 56 54 " src="https://user-images.githubusercontent.com/77574889/154605987-8e5bc6b8-198f-46f4-8dc1-b4b5f0f4ed8a.png">

**Comment by RodrigoTomeES** [comment]
Duplicate with https://github.com/ObuchiYuki/DevToysMac/issues/15
