### ISSUE TITLE
Checksum generator

### ISSUE THREAD

**Issue by jaroslavmraz** [ObuchiYuki/DevToysMac#65]
Checksum generator doing strang output. I have randomly download few files 

use mac shasum -a 256 filename and same in app but this sums dont match. shasum function geting right result but in devtools is a little different result.

TEST FILE: https://github.com/ObuchiYuki/DevToysMac/archive/refs/tags/0.0.7.2.tar.gz

SHASUM - 653029892428b59dfc66745d1400642393a3fd18a03a81b28e01284ba064cbca  DevToysMac-0.0.7.2.tar
DevToys -  653029892428b59dfc66745d140642393a3fd18a03a81b28e1284ba064cbca  

<img width="1228" alt="CHECKSUM-DONT-MATCH" src="https://user-images.githubusercontent.com/31340507/154677501-69b42670-be24-43f4-943a-39b8ba8dfb13.png">

**Comment by ObuchiYuki** [comment]
@jaroslavmraz Thank you for your issue! I solved this problem.

<img width="520" alt="スクリーンショット 2022-02-19 10 35 22" src="https://user-images.githubusercontent.com/20896810/154780868-61cfc985-aa7a-4606-9ce1-e4ea54c21d26.png">

This seem link hex convert bug. `0F` had been converted to `F`. I added the padding zero to fix this!

**Comment by ObuchiYuki** [comment]
@jaroslavmraz  Fixed on https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8
