### ISSUE TITLE
[Feature Request] Add color picker

### ISSUE THREAD

**Issue by namosuke** [ObuchiYuki/DevToysMac#66]
I want a color picker that can convert and output hex, rgb, hsl or hsv. I think color palette, alpha value support or gradation generator will be also good features for this.

**Comment by ObuchiYuki** [comment]
@namosuke  Added on https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8

<img width="1030" alt="スクリーンショット 2022-02-20 12 01 10" src="https://user-images.githubusercontent.com/20896810/154826672-d476441f-6bfe-49e0-a3e2-04a1c2253c5b.png">
<img width="1030" alt="スクリーンショット 2022-02-20 12 01 20" src="https://user-images.githubusercontent.com/20896810/154826676-d11fe59b-db29-4e1d-a6b8-9502ec16b92a.png">
<img width="1030" alt="スクリーンショット 2022-02-20 12 01 27" src="https://user-images.githubusercontent.com/20896810/154826677-c3f1df09-bf7f-4fcf-bca5-26ce3c28cdee.png">
