### ISSUE TITLE
Spanish translation doesn't work

### ISSUE THREAD

**Issue by RodrigoTomeES** [ObuchiYuki/DevToysMac#68]
Hi,

I think I made a mistake with the translation because it is not applied despite having the system in Spanish 😕. Does it work well with the other languages?

<img width="1185" alt="imagen" src="https://user-images.githubusercontent.com/13077343/154806319-a75d14f2-320b-418e-8509-6ce5f59134fa.png">

I am using the last version v.0.0.8

Thanks

**Comment by ObuchiYuki** [comment]
@RodrigoTomeES Sorry for that. It seems that the translation file was not loaded into the project. I have fixed the problem and would like to release it as 0.0.8.1.

**Comment by ObuchiYuki** [comment]
Fixed! 
https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8.1

**Comment by RodrigoTomeES** [comment]
@ObuchiYuki thanks for fix it! But I found that there is the same problem with main menu. How can I load the translations into the project? Also I found that the version of the app is incorrect. It show v.0.0.8.1 instead of v.0.0.8.2.

<img width="1512" alt="imagen" src="https://user-images.githubusercontent.com/13077343/154835102-6d2664ef-b2f7-4b9c-9bb8-4d30304c19df.png">
