### ISSUE TITLE
[BUG] Add multilingual support to color picker and settings page

### ISSUE THREAD

**Issue by RodrigoTomeES** [ObuchiYuki/DevToysMac#71]
Hi,

The strings that are contained in the files below should be extracted to translations files

 - [Setting view](https://github.com/ObuchiYuki/DevToysMac/blob/main/DevToys/DevToys/Body/SettingView%2B.swift)
 - [Color Picker view](https://github.com/ObuchiYuki/DevToysMac/blob/main/DevToys/DevToys/Body/Graphic/Color%20Picker/ColorPickerView%2B.swift)

Thanks!!

**Comment by ObuchiYuki** [comment]
@RodrigoTomeES Thanks for the issue! We've added multi-language support for ColorPicker, settings, etc. in 0.0.9! The new features are now supporting multilingual as well!
