### ISSUE TITLE
[Feature request] Compare JSON

### ISSUE THREAD

**Issue by MaxiTalenti** [ObuchiYuki/DevToysMac#78]

**Comment by RodrigoTomeES** [comment]
Hi, maybe you can use the feature diff text, that will be added in a near future #15

**Comment by ObuchiYuki** [comment]
@MaxiTalenti 
You can use the Text Diff feature of v0.0.10 now! https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.10
