### ISSUE TITLE
[Feature Request] Slugify 

### ISSUE THREAD

**Issue by chrissy-dev** [ObuchiYuki/DevToysMac#81]
Input: 
```
I'm a normal string with some Capital letters and spaces
```

Output: 
```
im-a-normal-string-with-some-capital-letters-and-spaces
```

[See here](https://blog.tersmitten.nl/slugify/)

**Comment by ObuchiYuki** [comment]
Thanks @chrissy-dev for the list! I've implemented Slugify as one of the features in Text Case Converter!

![画面収録 2022-02-26 10 40 10](https://user-images.githubusercontent.com/20896810/155823916-f373fc5f-56a0-4f79-a8e7-464db35c4fdd.gif)

**Comment by ObuchiYuki** [comment]
@chrissy-dev 

Added in v0.0.10! https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.10

**Comment by chrissy-dev** [comment]
@ObuchiYuki Fantastic 👍🏼  thanks.
